version: '3.8'
services: 
  postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: product
      POSTGRES_PORT: 5432
      #POSTGRES_HOST: 127.0.0.1

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@hepsinerede.com
      PGADMIN_DEFAULT_PASSWORD: toor